services:
  - type: web
    name: ezan-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    plan: free
    envVars:
      - key: PORT
        value: 10000
